### ISSUE TITLE
Create actionable statements (milestone 1)

### ISSUE THREAD

**Issue by svbagwell** [NASA-IMPACT/modern-dgf#26]
## Epic

- #19 

## Description

Create brief, actionable statements based on policies and mandates that will later be used to create the checks for the framework.

## Acceptance Criteria / To Do

- [x] PLRA (Jerika)
- [x] ULA (Jerika)
- [x] SPD-41a (Peng)
- [x] NASA Service Level Agreement (Shelby)
- [x] Open Government Data Act (Sumant/Peng)
- [x] Geospatial Data Act (Jerika/Sumant)
