### ISSUE TITLE
Create actionable statements (milestone 2)

### ISSUE THREAD

**Issue by svbagwell** [NASA-IMPACT/modern-dgf#28]
# Epic

- #20 

## Description

Create brief, actionable statements based on practices and guidelines that will later be used to create the checks for the framework.

## Acceptance Criteria / To Do

- [x] Data Products Development Guide (Shelby -- read the shorter version)
- [x] ADMG Data Stewardship (Jerika)
- [x] MLTD Strategy and Action Plan (Jerika)
- [x] O'FAIR ESDSWG Community FAIR Practices outline (Shelby)
- [x] [Dataset Interoperability Recommendations](https://www.earthdata.nasa.gov/esdis/eso/standards-and-references/dataset-interoperability-recommendations-for-earth-science) (Shelby)
